version: "3.9"

services:
  next:
    build:
      context: ./
      args:    
        - API_BASE=${API_BASE}
        - BACKEND_SERVER=${BACKEND_SERVER}
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
